### ISSUE TITLE
tcipher segfaults on ubuntu

### ISSUE THREAD

**Issue by sancelot** [gitwart/ciphertool#1] opened 2018-04-02 21:42 UTC
Compiling it on a ubuntu system (16.04 and > ) , the tcipher program crashes.

The problem does not happen when removing -DUSE_TCL_STUBS=1 from Makefile.

**Comment by gitwart** [comment] 2018-04-03 18:22
I'm setting up a Ubuntu 16.04 build machine to test this out.

**Comment by gitwart** [comment] 2018-04-04 01:59
I can confirm that I see the same problem, and that the tcipher executable also core dumps on Fedora 27.  I hadn't noticed this earlier because I always use the vanilla tclsh executable and 'package require' the extension.

I'll look at removing the stubs bits from the build system, which as you point out, should fix the issue.

**Comment by gitwart** [comment] 2018-04-04 12:46
Fixed in commit aa7c9557eb97998465c91fe7b1d88fb11d48cab5

**Closed as completed** 2018-05-18 11:58 UTC
